package irs2014.generalData;

import edu.wpi.first.wpilibj.SensorBase;


public interface PortRef {

	int DIP_SWITCH = 10;
	
	int JOYSTICK_1 = 1;
	int JOYSTICK_2 = 2;
	
	int SIDECAR_SLOT = SensorBase.getDefaultDigitalModule();
	int DIGITAL_IO = SensorBase.getDefaultSolenoidModule();
	int ANALOG_MODULE = SensorBase.getDefaultAnalogModule();
//	int SOLENOID_MODULE_PORT = SensorBase.getDefaultSolenoidModule();
	int SOLENOID_MODULE_PORT_1 = 1;
	int SOLENOID_MODULE_PORT_2 = 2;
	
	int ANALOG_PRESSURE_SENSOR = 4;
	
	int PORT_1 = 1;
	int PORT_2 = 2;
	int PORT_3 = 3;
	int PORT_4 = 4;
	
	int COMPETITION_TALON_R = 2;
	int COMPETITION_TALON_L = 1;

	int COMPETITION_ENCODER_R_A = 1;
	int COMPETITION_ENCODER_R_B = 2;

	int COMPETITION_ENCODER_L_A = 3;
	int COMPETITION_ENCODER_L_B = 4;
	
	int COMPETITION_COLLECTOR_MOTOR = 0; //TODO
	
	int COMPETITION_COLLECTOR_EXTENDER_SOLENOID_PORT = 0; //TODO
	int COMPETITION_COLLECTOR_RETRACTOR_SOLENOID_PORT = 0; //TODO
	
	int COMPETITION_COLLECTOR_LIMIT_SWITCH_PORT = 0; //TODO
	
	int COMPETITION_PRESSURE_SENSOR = 5; 
	
	int COMPETITION_SHOOTER_MIDDLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_MIDDLE_SOLENOID_RETRACTOR_PORT = 0; //TODO
	
	int COMPETITION_SHOOTER_INNER_SOLENOIDS_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_INNER_SOLENOIDS_RETRACTOR_PORT = 0; //TODO
	
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT_L = 1; //TODO
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT_L = 2; //TODO 
	
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT_R = 1; //TODO
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT_R = 2; //TODO 
	
	int COMPETITION_SHOOTER_ANGLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_ANGLE_SOLENOID_RETRACTOR_PORT = 0; //TODO

	
	int COMPETITION_PRESSURE_SWITCH_CHANNEL = 0; //TODO
	int COMPETITION_PRESSURE_SWITCH_SLOT = 0; //TODO
	int COMPETITION_COMPRESSOR_RELAY_SLOT = 0; //TODO
	int COMPETITION_COMPRESSOR_RELAY_CHANNEL = 0; //TODO
	
	int COMPETITION_LINE_SENSOR_PORT = -1; //TODO
	
	int PRACTICE_TALON_R = 2;
	int PRACTICE_TALON_L = 1;

	int PRACTICE_ENCODER_R_A = 1;///3;//4;	//Flipped right and left ports to fix competition bot 
	int PRACTICE_ENCODER_R_B = 5;///2;//5;	//Then flipped A and B for left and right to flip sign 

	int PRACTICE_ENCODER_L_A = 2;///5;//4;//2;//2;
	int PRACTICE_ENCODER_L_B = 3;///1;//5;//1;//3;
	
	int PRACTICE_COLLECTOR_MOTOR = 3; //TODO
	
	int PRACTICE_COLLECTOR_EXTENDER_SOLENOID_PORT = 4;//5; - for robot 
	int PRACTICE_COLLECTOR_RETRACTOR_SOLENOID_PORT = 5;//6; - for robot
	
	int PRACTICE_COLLECTOR_LIMIT_SWITCH_PORT = 0; //TODO
	
	int PRACTICE_PRESSURE_SENSOR = 7; 
	
	int PRACTICE_SHOOTER_MIDDLE_SOLENOID_EXTENDER_PORT = 5; //TODO
	int PRACTICE_SHOOTER_MIDDLE_SOLENOID_RETRACTOR_PORT = 6; //TODO
	
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_EXTENDER_PORT_L = 3; //TODO
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_RETRACTOR_PORT_L = 4; //TODO
	
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_EXTENDER_PORT_R = 7; //TODO
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_RETRACTOR_PORT_R = 8; //TODO
	
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT_L = 7;//1; //TODO
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT_L = 8;//2; //TODO 
	
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT_R = 1; //TODO
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT_R = 2; //TODO 
	
	int PRACTICE_SHOOTER_ANGLE_SOLENOID_EXTENDER_PORT = 4; //TODO
	int PRACTICE_SHOOTER_ANGLE_SOLENOID_RETRACTOR_PORT = 3; //TODO
	
	int PRACTICE_PRESSURE_SWITCH_CHANNEL = 0; //TODO
	int PRACTICE_PRESSURE_SWITCH_SLOT = 6; //TODO
	int PRACTICE_COMPRESSOR_RELAY_SLOT = 0; //TODO
	int PRACTICE_COMPRESSOR_RELAY_CHANNEL = 1; //TODO
	
	int PRACTICE_LINE_SENSOR_PORT = 9; //TODO
}
