package irs2014.generalData;

import edu.wpi.first.wpilibj.SensorBase;


public interface PortRef {
	int DIP_SWITCH = 14;
	
	int JOYSTICK_1 = 1;
	int JOYSTICK_2 = 2;
	
	int SIDECAR_SLOT = SensorBase.getDefaultDigitalModule();
	int DIGITAL_IO = SensorBase.getDefaultSolenoidModule();
	int SOLENOID_MODULE_PORT = SensorBase.getDefaultSolenoidModule();
	
	int PORT_1 = 1;
	int PORT_2 = 2;
	int PORT_3 = 3;
	int PORT_4 = 4;
	
	int COMPETITION_TALON_R = 2;
	int COMPETITION_TALON_L = 1;

	int COMPETITION_ENCODER_R_A = 1;
	int COMPETITION_ENCODER_R_B = 2;

	int COMPETITION_ENCODER_L_A = 3;
	int COMPETITION_ENCODER_L_B = 4;
	
	int COMPETITION_COLLECTOR_MOTOR = 0; //TODO
	
	int COMPETITION_COLLECTOR_EXTENDER_SOLENOID_PORT = 0; //TODO
	int COMPETITION_COLLECTOR_RETRACTOR_SOLENOID_PORT = 0; //TODO
	
	int COMPETITION_COLLECTOR_LIMIT_SWITCH_PORT = 0; //TODO
	
	int COMPETITION_PRESSURE_SENSOR = 5; 
	
	int COMPETITION_SHOOTER_MIDDLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_MIDDLE_SOLENOID_RETRACTOR_PORT = 0; //TODO
	
	int COMPETITION_SHOOTER_INNER_SOLENOIDS_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_INNER_SOLENOIDS_RETRACTOR_PORT = 0; //TODO
	
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT = 0; //TODO 
	
	int COMPETITION_SHOOTER_ANGLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int COMPETITION_SHOOTER_ANGLE_SOLENOID_RETRACTOR_PORT = 0; //TODO

	
	int COMPETITION_PRESSURE_SWITCH_CHANNEL = 0; //TODO
	int COMPETITION_PRESSURE_SWITCH_SLOT = 0; //TODO
	int COMPETITION_COMPRESSOR_RELAY_SLOT = 0; //TODO
	int COMPETITION_COMPRESSOR_RELAY_CHANNEL = 0; //TODO
	
	int PRACTICE_TALON_R = 2;
	int PRACTICE_TALON_L = 1;

	int PRACTICE_ENCODER_R_A = 1;
	int PRACTICE_ENCODER_R_B = 2;

	int PRACTICE_ENCODER_L_A = 3;
	int PRACTICE_ENCODER_L_B = 4;
	
	int PRACTICE_COLLECTOR_MOTOR = 0; //TODO
	
	int PRACTICE_COLLECTOR_EXTENDER_SOLENOID_PORT = 0; //TODO
	int PRACTICE_COLLECTOR_RETRACTOR_SOLENOID_PORT = 0; //TODO
	
	int PRACTICE_COLLECTOR_LIMIT_SWITCH_PORT = 0; //TODO
	
	int PRACTICE_PRESSURE_SENSOR = 5; 
	
	int PRACTICE_SHOOTER_MIDDLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int PRACTICE_SHOOTER_MIDDLE_SOLENOID_RETRACTOR_PORT = 0; //TODO
	
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_EXTENDER_PORT = 0; //TODO
	int PRACTICE_SHOOTER_INNER_SOLENOIDS_RETRACTOR_PORT = 0; //TODO
	
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_EXTENDER_PORT = 0; //TODO
	int PRACTICE_SHOOTER_OUTER_SOLENOIDS_RETRACTOR_PORT = 0; //TODO 
	
	int PRACTICE_SHOOTER_ANGLE_SOLENOID_EXTENDER_PORT = 0; //TODO
	int PRACTICE_SHOOTER_ANGLE_SOLENOID_RETRACTOR_PORT = 0; //TODO
	
	int PRACTICE_PRESSURE_SWITCH_CHANNEL = 0; //TODO
	int PRACTICE_PRESSURE_SWITCH_SLOT = 0; //TODO
	int PRACTICE_COMPRESSOR_RELAY_SLOT = 0; //TODO
	int PRACTICE_COMPRESSOR_RELAY_CHANNEL = 0; //TODO
}
