package irs2014.userInputDevices;

public interface ButtonRef {
	int EXTEND_COLLECTOR = -1; //TODO
	int RETRACT_COLLECTOR = -1; //TODO
	int COLLECTOR_MOTOR_IN = -1; //TODO
	int COLLECTOR_MOTOR_OUT = -1; //TODO
	int STOP_COLLECTOR_MOTOR = -1; //TODO
	
	int COLLECT_BALL = -1; //TODO
	int EJECT_BALL = -1; //TODO
	
	int EXTEND_ALL_SHOOTER_SOLENOIDS = -1; //TODO
	int EXTEND_INNER_SHOOTER_SOLENOIDS = -1; //TODO
	int EXTEND_INNER_THREE_SHOOTER_SOLENOIDS = -1; //TODO
	int EXTEND_MIDDLE_SHOOTER_SOLENOID = -1; //TODO
	int RETRACT_SHOOTER = -1; //TODO 
	int EXTEND_SHOOTER_ANGLE = -1; //TODO 
	int RETRACT_SHOOTER_ANGLE = -1; //TODO
	int SHOOTER_PULSE = -1; //TODO
	
	int GO_FORWARD = 3;
	
	//5 macros to detect sensors 
}
